on:  
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Replace path
      uses: jossef/action-set-json-field@v2.1
      with:
        file: event_calendar.json
        field: webcomponents[0].url   
        value: "/main.js"

    - name: Change development mode
      uses: jossef/action-set-json-field@v2.1
      with:
        file: event_calendar.json
        field: webcomponents[0].ignoreIntegrity  
        value: false
    
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'


    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "docs(): bumping release ${{ steps.semantic_release_info.outputs.git_tag }}"
        git tag ${{ steps.semantic_release_info.outputs.git_tag }}
        
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ github.token }}
        tags: true
        
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        allowUpdates: true
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}




