on:  
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Get SHA
      run: |
          SHA="sha256-$(shasum -a 256 main.js | awk '{print $1}' | xxd -r -p | base64)"
          echo "SHA=$SHA" >> $GITHUB_ENV

    - name: Replace path
      run: |
        jq '.webcomponents[0].url = "/main.js"' event_calendar.json > tmp.$$.json && mv tmp.$$.json event_calendar.json

    - name: Change development mode
      run: |
        jq '.webcomponents[0].ignoreIntegrity = false' event_calendar.json > tmp.$$.json && mv tmp.$$.json event_calendar.json

    - name: Generate SHA
      run: |
        jq --arg sha "$SHA" '.webcomponents[0].integrity = $sha' event_calendar.json > tmp.$$.json && mv tmp.$$.json event_calendar.json

    - name: Check changes
      run: |
          cat event_calendar.json
    
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        allowUpdates: true
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
