on:  
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Replace path
      uses: jossef/action-set-json-field@v2.1
      with:
        file: event_calendar.json
        field: webcomponents[0].url   
        value: "/main.js"

    - name: Change development mode
      uses: jossef/action-set-json-field@v2.1
      with:
        file: event_calendar.json
        field: webcomponents[0].ignoreIntegrity  
        value: false
    
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'


    - name: Commit changes
      run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add event_calendar.json
          git commit -m "Update URL field in JSON file"
          git tag ${{ steps.semantic_release_info.outputs.git_tag }}
          git push      
        
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        allowUpdates: true
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}




