on:  
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Update my-file.json description
      uses: jossef/action-set-json-field@v2.1
      with:
       file: event_calendar.json
       field: webcomponents[1].url
       value: /main.js
    
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
       artifacts: "release.zip"
       token: ${{ secrets.GITHUB_TOKEN }}



