on:  
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Get SHA
      run: |
           SHA=$(shasum -a 256 main.js | awk '{ print $1 }')
           echo "SHA=$SHA" >> $GITHUB_ENV


    - name: Replace path
      uses: jossef/action-set-json-field@v2.1
      with:
        file: event_calendar.json
        field: webcomponents.0.url   
        value: "/main.js"

    - name: Change development mode
      uses: jossef/action-set-json-field@v2.1
      with:
        file: event_calendar.json
        field: webcomponents.0.ignoreIntegrity  
        value: false

    - name: Generate SHA
      uses: jossef/action-set-json-field@v2.1
      with:
         file: event_calendar.json
         field: webcomponents.0.integrity  
         value: "${{ env.SHA }}" 
        

    - name: Check changes
      run: |
          cat event_calendar.json
    
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        
              
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        allowUpdates: true
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}




